
# client_config_backend: settings
# client_config:
#   client_id: "270608701232-kv7sengfie8e5gbihukjo0afni3glnvq.apps.googleusercontent.com"
#   client_secret: "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"

# save_credentials: True
# save_credentials_backend: file
# save_credentials_file: credentials.json

# get_refresh_token: True

# oauth_scope:
#   - https://www.googleapis.com/auth/drive.file
#   - https://www.googleapis.com/auth/drive.install
